### ISSUE TITLE
Doesn't work for me when closing  help windows using :close

### ISSUE THREAD

**Issue by eyalk5** [AndrewRadev/undoquit.vim#11]
Hi,

Cloud it made to work in this situation? 

I use 
noremap Q :close\<CR\>

**Comment by AndrewRadev** [comment]
The mapping should not be the problem, the issue here is that help files are special, and it's a bit iffy to try to restore them.

I've added some code to restore help buffers as well, although it positions them as normal windows (while the `:help` command tries to position them with a constant size in the same position, I think). Let me know if it works for you.

**Comment by eyalk5** [comment]
Thanks. I am using my own code eventually.

**Comment by AndrewRadev** [comment]
I don't understand what you mean? Does it work for you now? Or maybe you mean you no longer use this plugin?

**Comment by AndrewRadev** [comment]
I guess I'll close this then.
