### ISSUE TITLE
windows closed by commands such as `<c-w>c`

### ISSUE THREAD

**Issue by Konfekt** [AndrewRadev/undoquit.vim#6]
The undoclosewin.vim plugin also restores windows closed by commands such as `<c-w>c` or `ZZ`. Is it outside of the scope of undo_quit_.vim or is it impossible to implement this reliably ? 

If not, how about allowing undoquit to undo closes of windows by such commands as well (perhaps by taking a look at undoclosewin.vim's implementation) ?

**Comment by AndrewRadev** [comment]
From what I see, undoclosewin uses a different method. I'll see what I can do.

**Comment by AndrewRadev** [comment]
Hmm, undoclosewin seems to work in a more complicated way than I expected. It listens to the `BufWinLeave` event, but that one gets fired even when you're editing a new buffer in the same window :/. I guess this is why the internals of the plugin do some duplicate checks, although I'm not so sure how reliable they end up being...

Either way, this would be pretty complicated to support, so I think I won't implement it. In my experiments, `ZZ` works fine, it's only `<c-w>c` that doesn't throw a `QuitPre` autocommand. One way to get this working for you would be to remap `<c-w>c`:

``` vim
nnoremap <c-w>c :call undoquit#SaveWindowQuitHistory()<cr><c-w>c
```

This seems to work for me, but I wouldn't put it in the plugin, since I don'w want to override someone's mappings. Maybe I'll write it down as a tip in the documentation.

**Comment by suewonjp** [comment]
@AndrewRadev 
Thank you for a nice plugin!
This is a closed issue, but let me suggest an idea.
I've come up with the following quick and dirty fix to support `<C-w>c` and `:tabclose` as well as `:quit`. I tested the code and it seems working (but I didn't test it on every use case, though).
I think the code is simple enough to tell what the idea is all about but the idea is basically, letting the plugin support `WinClosed` event as well as `QuitPre`. (Please consider the fact that the code was written quickly only for a POC purpose) 

I'm not sure you'd like the idea, but I'd like to hear your thought.
I hope the plugin could support `<C-w>c` or `ZZ` or `ZQ` commands. (whether or not with my suggestion)

    diff --git a/autoload/undoquit.vim b/autoload/undoquit.vim
    index 078a872..38568f8 100644
    --- a/autoload/undoquit.vim
    +++ b/autoload/undoquit.vim
    @@ -1,6 +1,6 @@
    diff --git a/autoload/undoquit.vim b/autoload/undoquit.vim
    index 078a872..38568f8 100644
    --- a/autoload/undoquit.vim
    +++ b/autoload/undoquit.vim
    @@ -1,6 +1,6 @@
     " Stores the current window in the quit history, so we can undo the :quit
     " later.
    -function! undoquit#SaveWindowQuitHistory()
    +function! undoquit#SaveWindowQuitHistory(closed_window_data)
       if !s:IsStorable(bufnr('%'))
         return
       endif
    @@ -9,7 +9,11 @@ function! undoquit#SaveWindowQuitHistory()
         let g:undoquit_stack = []
       endif

    -  let window_data = undoquit#GetWindowRestoreData()
    +  if empty(a:closed_window_data)
    +    let window_data = undoquit#GetWindowRestoreData()
    +  else
    +    let window_data = a:closed_window_data
    +  endif

       call add(g:undoquit_stack, window_data)
     endfunction
    diff --git a/plugin/undoquit.vim b/plugin/undoquit.vim
    index f0ad7bd..70b10b2 100644
    --- a/plugin/undoquit.vim
    +++ b/plugin/undoquit.vim
    @@ -19,7 +19,11 @@ if !exists('g:undoquit_tab_mapping')
       let g:undoquit_tab_mapping = '<c-w>U'
     endif

    -autocmd QuitPre * call undoquit#SaveWindowQuitHistory()
    +let g:undoquit_closed_window_data = {}
    +
    +autocmd QuitPre * call undoquit#SaveWindowQuitHistory(0)
    +autocmd WinLeave * let g:undoquit_closed_window_data = undoquit#GetWindowRestoreData()
    +autocmd WinClosed * call undoquit#SaveWindowQuitHistory(g:undoquit_closed_window_data)

**Comment by AndrewRadev** [comment]
@suewonjp Unfortunately, after applying these changes, this fails 7 out of 13 test cases from the test suite for me. For instance, trying to open 3 buffers, closing the third and first, and then reopening them in sequence: https://github.com/AndrewRadev/undoquit.vim/blob/96935cae0c04ab9c7384afe1d2537ce883672e8c/spec/plugin/splits_spec.rb#L18-L33

I'm also not sure why use both `WinLeave` to store the data in a global variable, and then use `WinClosed` to actually save it. This patch only fails 5 out of 13 cases:

```
diff --git plugin/undoquit.vim plugin/undoquit.vim
index f0ad7bd..9a33b6b 100644
--- plugin/undoquit.vim
+++ plugin/undoquit.vim
@@ -19,7 +19,7 @@ if !exists('g:undoquit_tab_mapping')
   let g:undoquit_tab_mapping = '<c-w>U'
 endif
 
-autocmd QuitPre * call undoquit#SaveWindowQuitHistory()
+autocmd WinClosed * call undoquit#SaveWindowQuitHistory()
 
 command Undoquit    call undoquit#RestoreWindow()
 command UndoquitTab call undoquit#RestoreTab()
```

But it also fails, so that's not great :). I don't know if there are ways to work around this, but if you find any that pass the tests, feel free to open a new issue or PR.

**Comment by suewonjp** [comment]
@AndrewRadev 
Thank you for testing the idea anyway.
> I'm also not sure why use both WinLeave to store the data in a global variable, and then use WinClosed to actually save it. 

Yes. I know. It'll look weird.

When you call `undoquit#GetWindowRestoreData()` at `WinClosed` event, the function would return the data of the current window, not the closed window you have to restore later. I guess the previous  window is already out of view and cannot be retrieved at `WinClosed` event. (So the name `WinClosed`, I think)
However, you can get data of the window (which you're trying to close) at `WinLeave` event with call of `undoquit#GetWindowRestoreData()`
So you keep stashing the data of the target window at `WinLeave` event and save it at `WinClose` event.

I couldn't come up with better idea, but there might be one.

I'll dig it further later.

Thank you for your time.
