### ISSUE TITLE
macvim gui closed tabs won't undo

### ISSUE THREAD

**Issue by kevinlawler** [AndrewRadev/undoquit.vim#9]
In the latest MacVim, quitting a tab by clicking on the `X` on the tab GUI does not work. Quitting a tab with `:q` works.

**Comment by AndrewRadev** [comment]
That's a tricky issue. I don't have a mac, so I can't debug this on MacVim, but I think I can replicate it by using `:tabclose` (though I would appreciate if you confirm that `:tabclose` works the same way).

Unfortunately, listening for the `TabClosed` event doesn't give me the *previous* window, because it occurs *after* all of them have been closed, so I can't store the window positions and such. The `BufUnload` event will not be called upon hiding a buffer, so that one is tricky to manage. The `QuitPre` event is the only one that detects quitting a window (that I know of), but particularly for closing tabs with `:tabclose`, it doesn't seem be triggered :/.

My personal solution to this (which is actually a solution to a different problem) is a custom mapping that `:quit`s each window in the current tab: https://github.com/AndrewRadev/Vimfiles/blob/715652cff47cf2ec52989300f3eabe8e48796b50/startup/mappings.vim#L139-L149. 

I realize this isn't very general-purpose, but I can't think of any other way to get tab closing to work reliably. I'd call this a limitation of Vim, although if someone comes up with a workaround, I'll gladly try it out. I'm sorry that I can't be of more help.

**Comment by kevinlawler** [comment]
I think your analysis is right: this is a Vim limitation.

**Comment by AndrewRadev** [comment]
I've now implemented an `:UndoableTabclose` command that can at least be used as a replacement to the native `:tabclose`, allowing undoing -- you could check the documentation for details. But that probably doesn't change the issue, since I doubt there's a way to override the X on MacVim tabs.

In any case, I don't think there's anything I can do to help for this issue, so I'll close it for the moment.
